name = "ayllu/enrollment"
version = "0.0.0"
compiler = "v1.1.4"
plutus = "v2"
license = "Apache-2.0"
description = "Aiken contracts for project 'ayllu/enrollment'"

[repository]
user = "ayllu"
project = "enrollment"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "2.1.0"
source = "github"

[config]
